import { Room, UserProfile, Message } from "../types";

export const currentUserMock: UserProfile = {
  id: "usr_me_01",
  username: "raymon_degv",
  firstName: "Raymon",
  lastName: "Degv",
  phone: "4129876543",
  countryCode: "+58",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  bio: "Creador & Desarrollador de Degv's Messenger | Neón Glassmorphism ⚡",
  status: "online",
};

export const aiAssistantUser: UserProfile = {
  id: "usr_ai_assistant",
  username: "degvs_ai",
  firstName: "Degv's",
  lastName: "AI",
  phone: "+0000000000",
  countryCode: "+0",
  avatarUrl: "/icon-512.png",
  bio: "Asistente Oficial con Inteligencia Artificial Gemini 3.6 Flash ✨",
  status: "online",
  isAi: true,
};

export const mockUsersList: UserProfile[] = [
  aiAssistantUser,
  {
    id: "usr_carlos_02",
    username: "carlos_mendoza",
    firstName: "Carlos",
    lastName: "Mendoza",
    phone: "4141234567",
    countryCode: "+58",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    bio: "Apasionado por la tecnología y la mensajería en tiempo real 🚀",
    status: "online",
  },
  {
    id: "usr_mariana_03",
    username: "mariana_silva",
    firstName: "Mariana",
    lastName: "Silva",
    phone: "1551234567",
    countryCode: "+52",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    bio: "Diseñadora UX/UI | Degv's Messenger Fan 🎨",
    status: "offline",
    lastSeen: "Últ. vez hoy a las 16:45",
  },
  {
    id: "usr_andres_04",
    username: "andres_dev",
    firstName: "Andrés",
    lastName: "Torres",
    phone: "612345678",
    countryCode: "+34",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    bio: "Fullstack Engineer & PWA Specialist 📲",
    status: "online",
  },
];

export const initialMockRooms: Room[] = [
  {
    id: "room_ai_assistant",
    name: "Degv's AI (Asistente)",
    isAiChat: true,
    avatarUrl: aiAssistantUser.avatarUrl,
    participants: [aiAssistantUser],
    lastMessage: "¡Hola! Soy Degv's AI. ¿En qué te puedo ayudar hoy? Escribe o prueba /imagine para imágenes ✨",
    lastMessageTime: "17:45",
    unreadCount: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: "room_carlos",
    name: "Carlos Mendoza",
    avatarUrl: mockUsersList[1].avatarUrl,
    participants: [mockUsersList[1]],
    lastMessage: "¡Excelente interfaz con efecto cristal neón! 🔥",
    lastMessageTime: "17:30",
    unreadCount: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: "room_group_tech",
    name: "Equipo Degv's Tech 💻",
    isGroup: true,
    avatarUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=150&auto=format&fit=crop&q=80",
    participants: [mockUsersList[1], mockUsersList[2], mockUsersList[3]],
    lastMessage: "Mariana: Mencionen a @DegvIA para que resuma las notas del proyecto.",
    lastMessageTime: "16:15",
    unreadCount: 3,
    description: "Grupo oficial de desarrolladores de Degv's Messenger App.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "room_channel_news",
    name: "Canal Degv Official 📢",
    isChannel: true,
    avatarUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80",
    participants: [mockUsersList[0]],
    lastMessage: "🚀 Lanzamiento v3.0 con PWA instalable, notas de voz transcritas y cifrado.",
    lastMessageTime: "Ayer",
    unreadCount: 0,
    description: "Canal oficial de noticias y actualizaciones de la app.",
    createdAt: new Date().toISOString(),
  },
  {
    id: "room_mariana",
    name: "Mariana Silva",
    avatarUrl: mockUsersList[2].avatarUrl,
    participants: [mockUsersList[2]],
    lastMessage: "Te comparto la vista previa del prototipo en el chat.",
    lastMessageTime: "Ayer",
    unreadCount: 0,
    createdAt: new Date().toISOString(),
  },
];

export const initialMockMessages: Record<string, Message[]> = {
  room_ai_assistant: [
    {
      id: "msg_ai_01",
      roomId: "room_ai_assistant",
      senderId: "usr_ai_assistant",
      senderName: "Degv's AI",
      senderAvatar: aiAssistantUser.avatarUrl,
      content: "¡Bienvenido a Degv's Messenger! Soy tu Asistente IA potenciado con Gemini. Puedo responder preguntas, traducir mensajes, generar ideas, transcribir notas de voz y crear imágenes con el comando /imagine.",
      type: "text",
      createdAt: "17:40",
      isRead: true,
    },
  ],
  room_carlos: [
    {
      id: "msg_c_01",
      roomId: "room_carlos",
      senderId: "usr_carlos_02",
      senderName: "Carlos Mendoza",
      content: "¡Hola Raymon! Estuve probando el nuevo diseño Glassmorphism con neón verde.",
      type: "text",
      createdAt: "17:28",
      isRead: true,
    },
    {
      id: "msg_c_02",
      roomId: "room_carlos",
      senderId: "usr_me_01",
      senderName: "Raymon Degv",
      content: "¡Quedó espectacular! Además incluye transcripción de notas de voz por IA y PWA instalable.",
      type: "text",
      createdAt: "17:29",
      isRead: true,
    },
    {
      id: "msg_c_03",
      roomId: "room_carlos",
      senderId: "usr_carlos_02",
      senderName: "Carlos Mendoza",
      content: "¡Excelente interfaz con efecto cristal neón! 🔥",
      type: "text",
      createdAt: "17:30",
      isRead: false,
    },
  ],
  room_group_tech: [
    {
      id: "msg_g_01",
      roomId: "room_group_tech",
      senderId: "usr_mariana_03",
      senderName: "Mariana Silva",
      content: "¡Hola equipo! ¿Qué opinan sobre la votación para las nuevas encuestas?",
      type: "text",
      createdAt: "16:00",
      isRead: true,
    },
    {
      id: "msg_g_02",
      roomId: "room_group_tech",
      senderId: "usr_me_01",
      senderName: "Raymon Degv",
      content: "Acabo de crear una encuesta de prueba para que todos votemos.",
      type: "poll",
      poll: {
        id: "poll_01",
        question: "¿Cuál es tu función favorita de Degv's Messenger?",
        totalVotes: 3,
        options: [
          { id: "opt_1", text: "Degv's AI Chat & Menciones @DegvIA", votes: ["usr_carlos_02", "usr_mariana_03"] },
          { id: "opt_2", text: "Transcripción de Notas de Voz 🎙️", votes: ["usr_me_01"] },
          { id: "opt_3", text: "Bóveda Secreta con Biometría 🔒", votes: [] },
        ],
      },
      createdAt: "16:05",
      isRead: true,
    },
    {
      id: "msg_g_03",
      roomId: "room_group_tech",
      senderId: "usr_mariana_03",
      senderName: "Mariana Silva",
      content: "Mencionen a @DegvIA para que resuma las notas del proyecto.",
      type: "text",
      createdAt: "16:15",
      isRead: false,
    },
  ],
  room_channel_news: [
    {
      id: "msg_ch_01",
      roomId: "room_channel_news",
      senderId: "usr_ai_assistant",
      senderName: "Degv's Messenger Team",
      content: "🚀 Lanzamiento oficial de Degv's Messenger v3.0 con PWA instalable, notas de voz transcritas, cifrado de extremo a extremo y Bóveda Secreta.",
      type: "text",
      createdAt: "Ayer 10:00",
      isRead: true,
      reactions: [{ emoji: "🔥", userId: "usr_carlos_02", userName: "Carlos" }, { emoji: "🚀", userId: "usr_me_01", userName: "Raymon" }],
    },
  ],
};
